version: v1.0
triggers:
  - event: pull_request
global_job_config:
  setup:
    - echo Default Workflow
    - checkout
    - git rev-parse HEAD
    - neetoci-version ruby 3.1.3
    - neetoci-version node 18.12
    - bundle config path 'vendor/bundle'
    - bundle install
    # - bundle exec rails test
    - yarn add ramda
    - yarn add is-odd
    - yarn add react
  jobs:
    - name: Tests
      commands:
        - echo -e "\033[32mHello World\033[0m...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................."
        # - bundle exec rake db:create db:schema:load --trace